
# environment.yml
name: genexp
channels:
  - defaults
  - conda-forge
  - pytorch
  - bioconda
  - pyg
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pyg
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pyyaml
  - tqdm
  - matplotlib
  - cooler
  - tensorboard