name: gene_exp
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - numpy
      - pandas
      - scipy
      - scikit-learn
      - pyyaml
      - tqdm
      - matplotlib
      - cooler
      - tensorboard